FROM ubuntu:24.04
RUN apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends \
    blender libegl1 libgl1-mesa-dri && rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["blender"]
